### ISSUE TITLE
slice bounds out of range error in hip and hip_bench

### ISSUE THREAD

**Issue by xiaonanl** [emer/leabra#14]
When training running through the last epoch, it shows the attached error. I believe it's caused by ss.logrun function. 

panic: runtime error: slice bounds out of range [1:0]

goroutine 45 [running]:
main.(*Sim).LogRun(0x2a64240, 0xc0009ab770)
        C:/Users/Liu/OneDrive/UCD_Neuroscience/Modeling/leabra/examples/hip/hip.go:1527 +0x9d8
main.(*Sim).RunEnd(0x2a64240)
        C:/Users/Liu/OneDrive/UCD_Neuroscience/Modeling/leabra/examples/hip/hip.go:645 +0x45
main.(*Sim).TrainTrial(0x2a64240)
        C:/Users/Liu/OneDrive/UCD_Neuroscience/Modeling/leabra/examples/hip/hip.go:626 +0x1f2
main.(*Sim).TrainRun(0x2a64240)
        C:/Users/Liu/OneDrive/UCD_Neuroscience/Modeling/leabra/examples/hip/hip.go:794 +0x45
created by main.(*Sim).ConfigGui.func12
        C:/Users/Liu/OneDrive/UCD_Neuroscience/Modeling/leabra/examples/hip/hip.go:1736 +0x76

**Comment by rcoreilly** [comment]
hip.go:1527 is:

	epcix.Idxs = epcix.Idxs[epcix.Len()-nlast:]

looking at the logic, it is probably calling this with no values.  I'll just have it bail in that case.

**Comment by rcoreilly** [comment]
can you add the change I just checked in to your code and test?  I think this doesn't happen usually so something is causing it to happen in your case.  if it works, please close this ticket.

**Comment by xiaonanl** [comment]
this is solved.
