### ISSUE TITLE
leabra.Prjn does not implement emer.Prjn properly

### ISSUE THREAD

**Issue by rgobbel** [emer/leabra#16]
Looks like the return types on three methods are not right. Replacing lines 64-67 of leabra/prjn.go seems to fix it:

```Go
func (pj *Prjn) SetClass(cls string)          { pj.Cls = cls }
func (pj *Prjn) SetPattern(pat prjn.Pattern) emer.Prjn { pj.Pat = pat; return pj }
func (pj *Prjn) SetType(typ emer.PrjnType)    { pj.Typ = typ }
```

I've also started using this pattern to verify that my code is implementing interfaces correctly: 

```Go
 var _ emer.Prjn = (*Prjn)(nil) // for verification that the struct implements the interface
```

**Comment by rcoreilly** [comment]
you need to update emer/emergent/emer!  I updated the api
