### ISSUE TITLE
self.ConfigPats() call in ra25.py causes hangup so GUI doesn't open

### ISSUE THREAD

**Issue by thazy** [emer/leabra#3]
Using a fresh copy of `ra25.py` `pyleabra -i ra25.py` opens and runs correctly.  Replacing `self.OpenPats()` with `self.ConfigPats()` (in `self.Config()`) causes a hang so that the GUI doesn't open.  The log message shows something about a missing handle in the `_leabra` built-in module:
```
thazy@macbookpro ~/go/src/github.com/thazy/leabra_demo/ra25$ pyleabra -i ra25.py 
OpenGL version 4.1 NVIDIA-12.0.24 355.11.10.50.10.103
Traceback (most recent call last):
  File "ra25.py", line 1393, in <module>
    main(sys.argv[1:])
  File "ra25.py", line 1337, in main
    TheSim.Config()
  File "ra25.py", line 339, in Config
    self.ConfigPats()
  File "ra25.py", line 766, in ConfigPats
    patgen.PermutedBinaryRows(dt.Cols[1], 6, 1, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/leabra/patgen.py", line 67, in PermutedBinaryRows
    _leabra.patgen_PermutedBinaryRows(tsr.handle, nOn, onVal, offVal, goRun)
AttributeError: 'int' object has no attribute 'handle'
```

**Comment by thazy** [comment]
ADDENDUM: Here is the defn of `_leabra.patgen_PermutedBinaryRows()`.  It looks like maybe nOn has been assigned to be a handle type when all it really needed was a regular int? But maybe there's a reason it needs to be a handle?
```
patgen_PermutedBinaryRows(...)
        patgen_PermutedBinaryRows(tsr, nOn, onVal, offVal, goRun)
        
        type: tsr: int64_t
        type: nOn: int64_t
        type: onVal: double
        type: offVal: double
        type: goRun: bool
```

**Comment by rcoreilly** [comment]
for posterity: the err is from the `tsr.handle` expression, when`tsr` is *already* an int handle instead of a python wrapper around an int handle, which is what was expected there.  The source of the problem was `dt.Cols[1]` which was returning the int instead of the wrapper around the handle.  That was fixed in pr198 of gopy which has yet to be applied.  In case anyone else is looking at this, you need to do this in gopy to get the update:

```bash
$ cd ~/go/src/github.com/go-python/gopy  # use $GOPATH instead of ~/go if somewhere else
$ git fetch origin pull/198/head:pr198  # this gets the pull-request #198, into branch pr198
$ git checkout pr198  # switch to that branch
$ go install    # do go get -u ./... if this fails and try again -- installs gopy exe in ~go/bin
```
