### ISSUE TITLE
“Dependency & Build Issues with Leabra Installation: Cogent Core and Looper Module Errors on Linux”

### ISSUE THREAD

**Issue by Neologian** [emer/leabra#31]
Issue Summary:
I’m encountering multiple dependency and build errors while installing the Leabra package for cognitive modeling on Linux. The main issues seem to be related to the Cogent Core and Looper modules. I’m looking for guidance on resolving these errors or finding alternative approaches.

Details of the Setup:

	•	Repository: emer/leabra
	•	Environment: Linux, Go version 1.23.3
	•	Objective: Leabra’s capabilities are essential for my cognitive modeling projects, especially in relation to other cognitive architectures like ACT-R.

Challenges Encountered:

1. Cogent Core Dependency Error:

	•	Error Message:

go: cogentcore.org/core: unrecognized import path "cogentcore.org": parse https://cogentcore.org/?go-get=1: no go-import meta tags ()

	•	Attempted Solutions: Cloning Cogent Core into the project’s core directory did not resolve the error. Tried various import paths with no success.

2. Looper Module Not Found:

	•	Error Message:

go: github.com/emer/looper@latest: module github.com/emer/looper: git ls-remote -q origin ... exit status 128:
ERROR: Repository not found.

	•	Context: Go cannot locate the Looper module in the GitHub repository, which might indicate a recent path change or missing dependency.

3. Build Errors:

	•	Errors Encountered: Issues with several files (e.g., gabab_plot.go, nmda_plot.go, leabra.go), showing undefined methods and missing dependencies.
	•	Sample Error:

glong/gabab_plot/gabab.go:25:6: sim.VmRun undefined (type *Sim has no field or method VmRun)

Additional Context:

I’ve consulted the Leabra README and related documentation, but the available resources haven’t resolved the dependency and module issues. It seems that recent updates to Cogent Core and Looper may have affected compatibility.

Questions:

	1.	Recent Changes: Are there recent updates to the dependencies, especially Cogent Core and Looper, that could be causing these errors?
	2.	Updated Installation Guide: Is there an updated installation guide or recommended steps for handling these dependencies?
	3.	Alternative Installation Approaches: Are there alternative methods for managing these dependencies to avoid the current build errors?

Thank you for any help or guidance on this issue this community is able to impart.

**Comment by rcoreilly** [comment]
The latest version of the emer/leabra package is building correctly using go.mod modules, using standard "go build", as long as you have the prerequisites installed, per info at http://cogentcore.org/core -- best first step is to follow install instructions there.  We are using this for teaching and updating recently so I don't think anything in the current repo is out of date or anything -- it must be some kind of config / modules error or something.

**Comment by Neologian** [comment]
Thank you so much. This solves the issue and now everything is installed. Appreciate your timely response very much. Have a great day :)
