### ISSUE TITLE
ConfigGui() -> plot.Plot2D() brings Attribute Error in eplot.py, line 352

### ISSUE THREAD

**Issue by thazy** [emer/leabra#4]
Missing attribute in _leabra (?): eplot_Plot2D_CTor()

Screenshot from VSCode debugger:

<img width="632" alt="eplot py-Plot2D_bug25sep19" src="https://user-images.githubusercontent.com/30027010/65634396-5cb80700-df9b-11e9-9eec-dabe62d3f3d0.png">

**Comment by rcoreilly** [comment]
I'm definitely not getting this. are you sure you did a full make / install?  I rearranged python/Makefile -- did you perhaps have some local mods?  do git diff to ensure there are no diffs in your local copy after git pull etc.  also ensure that you're running the checked-in ra25.py.

**Comment by thazy** [comment]
Which .../python?  I did `make; make install` in both `.../goki/gi/python` and `.../emer/leabra/python`directories.  My new ra25.py has changes, e.g., new members in the Sim class:

```
self.InputValsTsr = 0
self.OutputValsTsr = 0
```

I'll do the git diff..

BTW, it also looks like you got rid of the single instance of `env` in `etable.py`, correct?

**Comment by rcoreilly** [comment]
yeah the etable include issue is now fixed -- that was a bit of a big job, but the fix is very general so it should be robust.  so are you getting it to work now?  If you don't have any changes, it really should work like mine does..

**Comment by thazy** [comment]
Thanks! Not working yet --  `git diff origin/master..master` in `.../emer/leabra`, `.../emer/emergent`, and `.../emer/etable` all returned nothing so I think that means no differences, but I'm not yet sure that's true.

Aside:  I noticed there is a second `gopy` fork at `.../goki/gopy` so I did a second `go install` there in case that mattered (not in instructions), but it didn't fix my problem.

**Comment by rcoreilly** [comment]
what are the diffs from this leabra.go file, from my emer/leabra/python/leabra dir:
[leabra.go.gz](https://github.com/emer/leabra/files/3656022/leabra.go.gz)

this has e.g.,:
```Go
//export eplot_Plot2D_CTor
func eplot_Plot2D_CTor() CGoHandle {
```

**Comment by rcoreilly** [comment]
also, it is key to do "make" from `emer/leabra/python` *not* from within the `leabra` dir under that!  the outer `Makefile` generates the `Makefile` within leabra and I have only checked in key changes to that outer one.  in general there is no reason to use the inner one -- not sure we should even be making it..

**Comment by thazy** [comment]
Re: diffs from this leabra.go:
```
thazy@macbookpro ~/go/src/github.com/emer/leabra$ git diff origin/master -- python/leabra/leabra.go master -- python/leabra/leabra.go
thazy@macbookpro ~/go/src/github.com/emer/leabra$
```
However, my leabra.go file has NOTHING even similar to:
```go
//export eplot_Plot2D_CTor
func eplot_Plot2D_CTor() CGoHandle {
``` 
SUBSEQUENTLY, I did another `make; make install` inside `.../emer/leabra/python' and there is still no sign of the eplot code block.  So, it seems the problem is that my `.../emer/leabra/python/leabra/leabra.go` file isn't getting updated appropriately for some reason.

QUESTION: For my understanding, is the `leabra.go` file in question something that should be updated with a `go get -u ./...` performed in the `.../emer/leabra` directory? OR, is it only generated at the `make; make install` step?

**Comment by thazy** [comment]
This looks potentially contributory:
```
thazy@macbookpro ~/go/src/github.com/emer/leabra$ go get -u ./...
# cd /Users/thazy/go/src/github.com/go-python/gopy; git pull --ff-only
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> pr198

package github.com/go-python/gopy/gopyh: exit status 1
thazy@macbookpro ~/go/src/github.com/emer/leabra$ 
```

Maybe I should do the suggested `git branch --set-upstream-to...pr198` command? Maybe my problem is that the pr198 isn't actually getting implemented?

**Comment by thazy** [comment]
PROGRESS! Informed by Randy's description of the process above I first removed the `Makefile` in `.../emer/leabra/python/leabra` and repeated `make; make install' in `.../python` -- but didn't work. SO THEN, I deleted the `Makefile` in `.../emer/leabra/python` and then did `.../emer/leabra/go get -u ./...` followed by `.../emer/leabra/python/make; ...make install` and VOILA! -- the `eplot_Plot2D_CTor(`code block has shown up in my `.../python/leabra/leabra.go` file. 

AND SO, I'm expecting things to work now -- will report later...

The IMPLICATION seems to be that `.../emer/leabra/go get -u ./...` command doesn't update the `.../python/Makefile` file for some reason. FYI, I DID check immediately after the `go get` and BEFORE the `make/make install` and a `Makefile` file was restored by the `go get` -- seems WEIRD that go get -u would skip updating the Makefile - but then again it's not a `go` file so maybe?!

**Comment by rcoreilly** [comment]
1. everything in `leabra/python/leabra` is generated by the 'make` command in `leabra/python`, including that `leabra.go`

2. doing `go get -u ./...` only works in a final exe dir like examples/ra25 -- otherwise you're not getting the full set of updates.

I'm not sure why it would even be pulling gopy for emer/leabra, but that does seem suspicious.

Although I just did the same command and got the same error message!

I tried doing the git command but got some weird  hints.  anyway, just saw you've made progress!

**Comment by thazy** [comment]
And FYI to be clear, I have not done the `git branch   --set-upstream-to=origin/<branch> pr198` command mentioned above.

**Comment by rcoreilly** [comment]
yeah you don't need the branch thing.

and in general I would recommend doing `git pull` instead of `go get -u ./...` on direct repositories that you're working on, e.g., emer/leabra -- it is more direct.  the go get is good for getting all the *other* dependencies but to make double sure you've got everything, do git pull and also git status and git diff to really see.  git diff should have shown you that your Makefile was not sync'd.

**Comment by thazy** [comment]
Re:  # 2. doing go get... above - that seems to maybe apply to the Makefile also?

**Comment by thazy** [comment]
`git pull` especially when dealing with directory trees that are not "pure" `go`.  I've come to realize that this python stuff is actually dealing with integrating three languages, including `C`.

**Comment by thazy** [comment]
CLOSURE:  Everything seems to be working for ra25.py now so I'm closing this issue.
