### ISSUE TITLE
User setting of maxTrials/maxEpochs ignored

### ISSUE THREAD

**Issue by rohrlich** [emer/leabra#7]
I think the Init() is resetting them by calling SetParams - not sure.

**Comment by rcoreilly** [comment]
in the default ra25 example, there is a param setting that does indeed overwrite that value -- it is there to demonstrate that you can change Sim values in addition to network ones.  I agree it is confusing but I also want to have that demo.. anyway, in your model you can get rid of that param value and it should reflect what you put in..
